services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      network: host
    restart: unless-stopped
    ports:
      - "8081:8081"
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_DB: tourplanner
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
